### ISSUE TITLE
一些不懂的问题

### ISSUE THREAD

**Issue by Gginmiao** [haoranliu666/BuyTicket_ZhuHaiHongKong#1]
Select Copy as cURL (cmd) or (bash)？
如果我需要预订两个人的车票如果做？
在您的code 里 #command need to be replaced# 但readme 没有说明变更为什么？

**Comment by haoranliu666** [comment]
想订两张票，就需要检查到两张空白票。
把从chrome里复制的cURL，变成python里的字符串，放到command里
